spring.application.name=finance-app
server.port=${PORT:8080}
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=postgres
spring.datasource.password=aidai123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (use a strong base64 key ? generate at https://www.browserling.com/tools/base64)
jwt.secret=YourBase64EncodedSecretKeyHereAtLeast32Bytes
jwt.expiration.ms=86400000
